[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.4"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs","jose","uuid"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
