
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[functions."alerts-check"]
  # If you prefer TOML scheduling instead of inline config:
  # schedule = "@hourly"

[[edge_functions]]
  path = "/sse/:room"
  function = "chat-sse"

# SPA fallback if not using _redirects file
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
