
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/sse/:room"
  function = "chat-sse"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
