[build]
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"

functions = "netlify/functions"
edge_functions = "netlify/edge-functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.png"
  status = 200

[[edge_functions]]
  function = "chat-sse"
  path = "/sse/:room"
